### ISSUE TITLE
Promo.pl Merge fail

### ISSUE THREAD

**Issue by florentBourgeois** [Namhto/Projet-3A#2]
Attention, un merge vers la branche master à été complètement raté, ce qui a donné un fichier avec des notes Git dedans signalant les conflits non gérés (promo.pl)

**Comment by Namhto** [comment]
Oui on a remarqué ça en voulant commit...
Je sais pas vraiment résoudre les conflit sur Git donc on a bossé en local :/

J'essaie de réglé le conflis

**Comment by florentBourgeois** [comment]
Suivant l'interface que vous utilisez pour gérer votre git c'est plus ou moins simple.

Comme toujours, c'est l'utilisation de la console et de commandes qui est le plus puissant. Mais tout le monde n'est pas assez fou pour s'amuser à prendre ca en main.
J'utilise personnellement smartgit qui est assez sympathique quand on ne cherche pas trop loin et qui permet, lors de l'apparition de conflits,  de sélectionner quelle partie du code on préfère garder (la head ou la notre)
j'ai eu beaucoup d'échos positifs concernant totoiseGit pour window.
Je sais que avec mes collègue pour travailler à 7 sur le meme projet on utilisait majoritairement sourcetree qui fait très bien le boulot.
