### ISSUE TITLE
Contraintes => Pas de duplicata

### ISSUE THREAD

**Issue by florentBourgeois** [Namhto/Projet-3A#7]
Pour un créneau donné il ne faut pas que le prof / les étudiants / la salle ne soient dans plusieurs cours en même temps.

Cette contrainte induit implicitement que le même cours ne peut pas avoir lieux plusieurs fois en même temps puisque le prof et les étudiants qui y participent ne peuvent l'être.

**Comment by Namhto** [comment]
Commit : 
694d80222dc8221216dcbf8e2ad924c28bc4c40c
